import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Autogenerated from the folder structure, so adding a page needs no config
// change. Order is controlled by sidebar_position front matter.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
